// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3b-FATdFc_m1tgy7XkBIsW4Gg93aKOVk',
    appId: '1:450522985564:android:dfe29e5807daee61f1e299',
    messagingSenderId: '450522985564',
    projectId: 'nuhkm1',
    storageBucket: 'nuhkm1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD0i8pkAzC3jBZHKxCVmKqeUbhooEevvI',
    appId: '1:450522985564:ios:ec99c3cccd3a5790f1e299',
    messagingSenderId: '450522985564',
    projectId: 'nuhkm1',
    storageBucket: 'nuhkm1.firebasestorage.app',
    androidClientId: '450522985564-q9m6oudmcqip4a70eucvmhs6jqala66u.apps.googleusercontent.com',
    iosClientId: '450522985564-jh4vg2cqvd3kgkieoq6bedkq6icfm7c3.apps.googleusercontent.com',
    iosBundleId: 'com.legal.nahkum',
  );
}
